name: example
description: A project used to demo the fmvvm
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fmvvm_annotation:
    path: ../fmvvm_annotation/

dev_dependencies:
  build_runner: ^2.4.6
  fmvvm_generator:
    path: ../fmvvm_generator/