builders:
  fmvvm_generator:
    import: "package:fmvvm_generator/fmvvm_generator.dart"
    builder_factories: ["fmvvm"]
    build_extensions: { ".dart": [".fmvvm.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]